<?php

namespace Database\Seeders;

use App\Models\AiPrompt;
use App\Models\AiPromptCategory;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Seeder;

class AiPromptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Schema::disableForeignKeyConstraints();
        AiPromptCategory::truncate();
        AiPrompt::truncate();
        Schema::enableForeignKeyConstraints();

        $categories = [
            [
                'id' => 1,
                'name' => 'Image Generation',
                'slug' => 'image-generation',
                'description' => 'Prompts for creating viral images, art, thumbnails, and visual designs using AI.',
                'image' => null,
                'meta_description' => 'Browse AI prompts for image generation. Create viral AI art, thumbnails, posters, and visual designs.',
                'meta_keywords' => 'AI image prompts, Midjourney prompts, AI art prompts, viral image prompts',
                'sort_order' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Video Creation',
                'slug' => 'video-creation',
                'description' => 'Prompts for generating video ideas, scripts, storyboards, and viral short-form content.',
                'image' => null,
                'meta_description' => 'Discover AI prompts for video creation. Generate viral reels, shorts, YouTube scripts, and storyboards.',
                'meta_keywords' => 'AI video prompts, YouTube script prompts, reels prompts, shorts prompts',
                'sort_order' => 2,
            ],
            [
                'id' => 3,
                'name' => 'Writing & Content',
                'slug' => 'writing-content',
                'description' => 'Prompts for articles, blogs, newsletters, and creative writing.',
                'image' => null,
                'meta_description' => 'Browse AI prompts for writing and content creation. Blog outlines, simplification, and creative writing.',
                'meta_keywords' => 'AI writing prompts, blog prompts, content writing, creative writing',
                'sort_order' => 3,
            ],
            [
                'id' => 4,
                'name' => 'Marketing & Growth',
                'slug' => 'marketing-growth',
                'description' => 'Prompts for ads, landing pages, funnels, and growth strategies.',
                'image' => null,
                'meta_description' => 'Explore AI prompts for marketing and growth. Create ad copy, funnels, and growth strategies using AI.',
                'meta_keywords' => 'AI marketing prompts, ad copy prompts, growth hacking prompts, funnel prompts',
                'sort_order' => 4,
            ],
            [
                'id' => 5,
                'name' => 'Business & Startup',
                'slug' => 'business-startup',
                'description' => 'Prompts for startup ideas, market research, planning, and business strategy.',
                'image' => null,
                'meta_description' => 'Find AI prompts for startups and business planning. Validate ideas, analyze competitors, and plan growth.',
                'meta_keywords' => 'startup prompts, business planning prompts, AI business prompts, idea validation prompts',
                'sort_order' => 5,
            ],
            [
                'id' => 6,
                'name' => 'Coding & Development',
                'slug' => 'coding-development',
                'description' => 'Prompts for code generation, debugging, refactoring, and system design.',
                'image' => null,
                'meta_description' => 'Browse AI prompts for coding and development. Generate code, debug errors, and design systems with AI.',
                'meta_keywords' => 'AI coding prompts, programming prompts, debug prompts, code generation prompts',
                'sort_order' => 6,
            ],
            [
                'id' => 7,
                'name' => 'Social Media',
                'slug' => 'social-media',
                'description' => 'Prompts for creating posts, captions, hooks, and content calendars for social platforms.',
                'image' => null,
                'meta_description' => 'Explore AI prompts for social media content. Create viral posts, captions, hooks, and content calendars.',
                'meta_keywords' => 'social media prompts, Instagram prompts, TikTok prompts, content calendar prompts',
                'sort_order' => 7,
            ],
            [
                'id' => 8,
                'name' => 'Productivity & Life',
                'slug' => 'productivity-life',
                'description' => 'Prompts for planning, habits, learning, and personal improvement.',
                'image' => null,
                'meta_description' => 'Discover AI prompts for productivity and life improvement. Plan goals, build habits, and learn faster.',
                'meta_keywords' => 'productivity prompts, habit building prompts, learning prompts, self improvement prompts',
                'sort_order' => 8,
            ],
            [
                'id' => 9,
                'name' => 'Ecommerce',
                'slug' => 'ecommerce',
                'description' => 'Prompts for product descriptions, store setup, customer support, and sales optimization.',
                'image' => null,
                'meta_description' => 'Browse AI prompts for ecommerce. Create product descriptions, improve conversions, and automate customer support.',
                'meta_keywords' => 'ecommerce prompts, product description prompts, shopify prompts, conversion prompts',
                'sort_order' => 9,
            ],
            [
                'id' => 10,
                'name' => 'Research & Learning',
                'slug' => 'research-learning',
                'description' => 'Prompts for studying, summarizing information, and building learning roadmaps.',
                'image' => null,
                'meta_description' => 'Explore AI prompts for research and learning. Summarize content, understand topics, and create study plans.',
                'meta_keywords' => 'study prompts, research prompts, summarize prompts, learning roadmap prompts',
                'sort_order' => 10,
            ],
            [
                'id' => 11,
                'name' => 'AI Automation & Workflows',
                'slug' => 'ai-automation-workflows',
                'description' => 'Prompts for building AI workflows, multi-step processes, and automation systems.',
                'image' => null,
                'meta_description' => 'Find AI prompts for automation and workflows. Create multi-step AI processes and automated tasks.',
                'meta_keywords' => 'AI automation prompts, workflow prompts, agent prompts, multi step prompts',
                'sort_order' => 11,
            ],
            [
                'id' => 12,
                'name' => 'Prompt Engineering',
                'slug' => 'prompt-engineering',
                'description' => 'Advanced prompts for system messages, structured outputs, and multi-turn interactions.',
                'image' => null,
                'meta_description' => 'Browse advanced AI prompt engineering templates. Create system prompts and structured output prompts.',
                'meta_keywords' => 'prompt engineering, system prompts, structured output prompts, few shot prompts',
                'sort_order' => 12,
            ],
            [
                'id' => 13,
                'name' => 'Fun & Creative',
                'slug' => 'fun-creative',
                'description' => 'Prompts for games, stories, roleplay, and creative experiments with AI.',
                'image' => null,
                'meta_description' => 'Discover fun and creative AI prompts. Play games, write stories, and experiment with AI creativity.',
                'meta_keywords' => 'AI games prompts, roleplay prompts, story prompts, creative AI prompts',
                'sort_order' => 13,
            ],
            
        ];

        foreach ($categories as $cat) {
            AiPromptCategory::updateOrCreate(
                ['slug' => $cat['slug']],
                array_merge($cat, ['is_active' => true])
            );
        }

        $prompts = [
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-viral-portrait-neon',
                'slug' => 'viral-neon-portrait',
                'title' => 'Viral Neon Portrait Generator',
                'description' => 'Create a cinematic neon-lit portrait suitable for viral social media posts.',
                'image' => null,
                'meta_description' => 'Generate viral neon portrait images using AI. Perfect for Instagram, profile pictures, and creative portraits.',
                'meta_keywords' => 'neon portrait prompt, viral ai image, cinematic portrait, ai art portrait',
                'prompt' => "Create a highly detailed cinematic portrait of a person with neon lighting, cyberpunk color tones, dramatic shadows, shallow depth of field, ultra high resolution, soft rim light, professional photography style. Subject description: [DESCRIBE PERSON]. Background: futuristic city lights.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-youtube-thumbnail-viral',
                'slug' => 'viral-youtube-thumbnail',
                'title' => 'Viral YouTube Thumbnail Creator',
                'description' => 'Generate eye-catching YouTube thumbnail images with bold expressions and high contrast.',
                'image' => null,
                'meta_description' => 'Create viral YouTube thumbnails using AI prompts. High-contrast faces, bold emotions, and click-worthy designs.',
                'meta_keywords' => 'youtube thumbnail prompt, viral thumbnail ai, clickbait thumbnail, ai thumbnail generator',
                'prompt' => "Generate a high-contrast, eye-catching YouTube thumbnail featuring a person with an exaggerated facial expression (shock, excitement, curiosity), bold lighting, vibrant colors, clean background, strong subject focus, studio lighting, ultra sharp, optimized for small screens. Topic text concept: [VIDEO TOPIC].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-product-mockup-clean',
                'slug' => 'clean-product-mockup',
                'title' => 'Clean Product Mockup Generator',
                'description' => 'Create professional product mockups for ecommerce and landing pages.',
                'image' => null,
                'meta_description' => 'Generate clean product mockups using AI. Perfect for ecommerce product pages and marketing visuals.',
                'meta_keywords' => 'product mockup prompt, ecommerce ai images, product photography ai, mockup generator',
                'prompt' => "Create a professional product mockup photo of [PRODUCT NAME] on a minimal clean background, soft studio lighting, subtle shadows, realistic textures, commercial product photography style, high resolution, centered composition, suitable for ecommerce product listing.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-anime-character-viral',
                'slug' => 'viral-anime-character',
                'title' => 'Viral Anime Character Art',
                'description' => 'Generate high-quality anime-style character illustrations with dramatic lighting.',
                'image' => null,
                'meta_description' => 'Create viral anime character art using AI prompts. High detail, dramatic lighting, and cinematic backgrounds.',
                'meta_keywords' => 'anime ai prompt, anime character generator, ai anime art, manga style ai',
                'prompt' => "Create an anime-style character illustration with ultra detailed facial features, expressive eyes, dynamic pose, dramatic cinematic lighting, vibrant color palette, soft glow effects, high resolution, trending anime art style. Character concept: [CHARACTER DESCRIPTION]. Background: [SCENE].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-logo-minimal-modern',
                'slug' => 'minimal-modern-logo',
                'title' => 'Minimal Modern Logo Generator',
                'description' => 'Design minimal and modern logo concepts using AI image generation.',
                'image' => null,
                'meta_description' => 'Generate minimal modern logo designs using AI. Great for startups, apps, and brands.',
                'meta_keywords' => 'logo design prompt, minimal logo ai, startup logo ai, modern logo generator',
                'prompt' => "Design a minimal modern logo for a brand named [BRAND NAME]. Style: clean, geometric, flat design, monochrome or limited color palette, professional branding aesthetic, high resolution, suitable for app icon and website header. Brand theme: [BRAND THEME].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 1,
                'unique_id' => 'img-cinematic-wallpaper-4k',
                'slug' => 'cinematic-4k-wallpaper',
                'title' => 'Cinematic 4K Wallpaper Generator',
                'description' => 'Create cinematic 4K wallpapers for desktop and mobile backgrounds.',
                'image' => null,
                'meta_description' => 'Generate cinematic 4K wallpapers using AI. Perfect for desktop, mobile backgrounds, and digital art.',
                'meta_keywords' => '4k wallpaper ai, cinematic wallpaper prompt, ai background images, aesthetic wallpaper ai',
                'prompt' => "Create a cinematic 4K wallpaper of [SCENE OR LOCATION] with dramatic lighting, atmospheric depth, ultra wide composition, volumetric light rays, high detail environment, realistic textures, moody color grading, professional cinematic concept art style.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-viral-short-hook',
                'slug' => 'viral-short-hook-generator',
                'title' => 'Viral Short Hook Generator',
                'description' => 'Generate powerful hooks for short-form videos to grab attention in the first 3 seconds.',
                'image' => null,
                'meta_description' => 'Create viral hooks for shorts and reels using AI. Grab attention in the first 3 seconds of your video.',
                'meta_keywords' => 'viral hook prompts, shorts hook ai, reels hook generator, tiktok hook prompts',
                'prompt' => "Generate 10 short, punchy hooks for a viral short-form video about: [TOPIC]. Each hook must be under 12 words, emotionally engaging, curiosity-driven, and optimized to stop scrolling in the first 3 seconds.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-youtube-script-structured',
                'slug' => 'youtube-video-script-generator',
                'title' => 'YouTube Video Script Generator',
                'description' => 'Create a complete, engaging YouTube video script with hook, structure, and CTA.',
                'image' => null,
                'meta_description' => 'Generate structured YouTube video scripts with hook, main points, and call-to-action using AI.',
                'meta_keywords' => 'youtube script prompt, video script ai, youtube content prompts, video scripting ai',
                'prompt' => "Write a complete YouTube video script for the topic: [TOPIC]. Include: 1) A strong hook in the first 5 seconds, 2) Clear sectioned structure with timestamps, 3) Engaging storytelling and examples, 4) A concise CTA at the end. Keep tone conversational and energetic.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-faceless-channel-script',
                'slug' => 'faceless-channel-script',
                'title' => 'Faceless Channel Script Creator',
                'description' => 'Generate scripts for faceless YouTube or TikTok channels with narration and visuals.',
                'image' => null,
                'meta_description' => 'Create faceless channel scripts using AI. Perfect for YouTube automation and voiceover videos.',
                'meta_keywords' => 'faceless channel prompts, youtube automation script, voiceover script ai, faceless video ideas',
                'prompt' => "Create a faceless video script for the topic: [TOPIC]. Include: 1) Engaging narration text, 2) Scene-by-scene visual suggestions, 3) Background music mood suggestions, 4) On-screen text captions for key moments. Optimize for retention and clarity.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-storyboard-generator',
                'slug' => 'video-storyboard-generator',
                'title' => 'Video Storyboard Generator',
                'description' => 'Generate a structured storyboard for video scenes and transitions.',
                'image' => null,
                'meta_description' => 'Create video storyboards using AI. Plan scenes, camera angles, transitions, and pacing.',
                'meta_keywords' => 'video storyboard prompt, ai storyboard generator, video planning prompts, scene planning ai',
                'prompt' => "Create a detailed storyboard for a video about: [TOPIC]. Break it into 6–8 scenes. For each scene, include: 1) Visual description, 2) Camera angle or shot type, 3) On-screen text, 4) Transition to next scene. Keep pacing engaging and cinematic.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-reel-idea-generator',
                'slug' => 'viral-reel-idea-generator',
                'title' => 'Viral Reel Ideas Generator',
                'description' => 'Generate viral Instagram Reels and TikTok content ideas for any niche.',
                'image' => null,
                'meta_description' => 'Discover viral reel ideas using AI. Generate high-engagement concepts for Instagram and TikTok.',
                'meta_keywords' => 'reels ideas ai, tiktok ideas prompts, viral content ideas ai, short video ideas',
                'prompt' => "Generate 15 viral short-form video ideas for the niche: [NICHE]. Each idea should include: 1) A hook concept, 2) The main action or twist, 3) The emotional trigger (curiosity, shock, humor, inspiration). Keep ideas short and highly shareable.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 2,
                'unique_id' => 'vid-broll-shotlist',
                'slug' => 'broll-shotlist-generator',
                'title' => 'B-Roll Shot List Generator',
                'description' => 'Generate a B-roll shot list to enhance video storytelling and production quality.',
                'image' => null,
                'meta_description' => 'Create B-roll shot lists using AI. Improve video quality with cinematic supporting shots.',
                'meta_keywords' => 'b-roll shot list prompt, video production prompts, cinematic b-roll ideas, shot list generator',
                'prompt' => "Create a B-roll shot list for a video about: [TOPIC]. Provide 10–15 supporting shots with camera angles, motion suggestions, lighting mood, and how each shot supports the main story or message.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-blog-outline-structured',
                'slug' => 'blog-outline-generator',
                'title' => 'Blog Post Outline Generator',
                'description' => 'Generate a structured outline for a blog post with intro, sections, and CTA.',
                'image' => null,
                'meta_description' => 'Free AI prompt to generate a detailed blog post outline with hook, sections, and CTA. Use for any topic.',
                'meta_keywords' => 'blog outline, content outline, AI writing, blog structure',
                'prompt' => "Create a detailed blog post outline for the topic: [TOPIC]. Include: 1) A hook for the introduction, 2) 3–5 main sections with sub-points, 3) Key takeaways or bullet list, 4) A strong call-to-action. Keep each section concise and actionable.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-seo-blog-draft',
                'slug' => 'seo-blog-post-draft',
                'title' => 'SEO-Friendly Blog Post Draft',
                'description' => 'Generate an SEO-optimized blog post draft for any topic.',
                'image' => null,
                'meta_description' => 'Create SEO-friendly blog posts using AI prompts. Generate drafts optimized for search engines and readers.',
                'meta_keywords' => 'seo blog prompt, blog writing ai, content writing ai, seo content generator',
                'prompt' => "Write an SEO-optimized blog post draft about: [TOPIC]. Include: 1) An engaging introduction, 2) Clear H2 and H3 headings, 3) Natural use of primary keyword: [PRIMARY KEYWORD], 4) Practical examples, 5) A short conclusion with CTA. Keep tone informative and easy to read.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-social-post-ideas',
                'slug' => 'social-post-ideas-generator',
                'title' => 'Social Media Post Ideas Generator',
                'description' => 'Generate creative post ideas for social media content calendars.',
                'image' => null,
                'meta_description' => 'Generate social media post ideas using AI. Create engaging content ideas for any platform.',
                'meta_keywords' => 'social media ideas, content calendar prompts, post ideas ai, social content generator',
                'prompt' => "Generate 15 creative social media post ideas for the niche: [NICHE]. For each idea, include: 1) Post concept, 2) Hook line, 3) Suggested content format (image, carousel, short video, text). Optimize for engagement and shareability.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-headline-variations',
                'slug' => 'headline-variations-generator',
                'title' => 'Headline Variations Generator',
                'description' => 'Create multiple headline variations for blogs, ads, or landing pages.',
                'image' => null,
                'meta_description' => 'Generate catchy headline variations using AI. Improve click-through rate for blogs, ads, and landing pages.',
                'meta_keywords' => 'headline generator, title ideas ai, copywriting prompts, clickbait headline ai',
                'prompt' => "Generate 20 headline variations for the topic: [TOPIC]. Include a mix of curiosity-driven, benefit-focused, and emotional headlines. Keep each headline under 12 words and optimized for high click-through rates.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-content-repurpose',
                'slug' => 'content-repurpose-generator',
                'title' => 'Content Repurposing Assistant',
                'description' => 'Repurpose long-form content into multiple short-form formats.',
                'image' => null,
                'meta_description' => 'Repurpose blogs or videos into social posts, threads, and captions using AI prompts.',
                'meta_keywords' => 'content repurposing ai, repurpose blog to social, content reuse prompts, ai content workflow',
                'prompt' => "Repurpose the following content into: 1) 3 Twitter/X posts, 2) 2 LinkedIn posts, 3) 1 Instagram caption. Keep the core message, adapt tone for each platform, and include relevant hooks. Content: [PASTE CONTENT].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 3,
                'unique_id' => 'write-email-newsletter',
                'slug' => 'email-newsletter-generator',
                'title' => 'Email Newsletter Generator',
                'description' => 'Generate engaging email newsletters with subject lines and CTAs.',
                'image' => null,
                'meta_description' => 'Create engaging email newsletters using AI prompts. Generate subject lines, body content, and CTAs.',
                'meta_keywords' => 'email newsletter ai, email writing prompts, newsletter generator, email copywriting ai',
                'prompt' => "Write an engaging email newsletter for the topic: [TOPIC]. Include: 1) 3 subject line options, 2) A short personal intro, 3) Main content section with value-driven tips, 4) A clear CTA. Keep tone friendly and concise.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-landing-page-copy',
                'slug' => 'landing-page-copy-generator',
                'title' => 'Landing Page Copy Generator',
                'description' => 'Generate high-converting landing page copy with clear sections and CTAs.',
                'image' => null,
                'meta_description' => 'Create high-converting landing page copy using AI prompts. Generate headlines, benefits, and CTAs.',
                'meta_keywords' => 'landing page copy ai, conversion copywriting prompts, landing page generator, ai marketing copy',
                'prompt' => "Write high-converting landing page copy for: [PRODUCT OR SERVICE]. Include: 1) Hero headline + subheadline, 2) Key benefits (bullet points), 3) Social proof placeholders, 4) Objection handling, 5) Clear call-to-action. Optimize for clarity and conversions.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-ad-copy-variants',
                'slug' => 'ad-copy-variants-generator',
                'title' => 'Ad Copy Variations Generator',
                'description' => 'Generate multiple ad copy variations for paid ads across platforms.',
                'image' => null,
                'meta_description' => 'Generate ad copy variations using AI prompts. Create high-performing ads for Facebook, Google, and Instagram.',
                'meta_keywords' => 'ad copy ai, facebook ad prompts, google ads copy, paid ads generator',
                'prompt' => "Generate 10 ad copy variations for [PRODUCT OR SERVICE] targeting [TARGET AUDIENCE]. Include: 1) Primary text, 2) Headline, 3) Short CTA. Optimize for clarity, benefits, and emotional triggers. Avoid generic marketing language.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-growth-strategy-plan',
                'slug' => 'growth-strategy-plan',
                'title' => 'Growth Strategy Planner',
                'description' => 'Create a practical growth plan with channels, experiments, and metrics.',
                'image' => null,
                'meta_description' => 'Generate growth strategies using AI prompts. Plan channels, experiments, and metrics for product growth.',
                'meta_keywords' => 'growth strategy ai, marketing plan prompts, growth hacking plan, user acquisition prompts',
                'prompt' => "Create a 30-day growth strategy plan for: [PRODUCT OR SERVICE]. Include: 1) 3 main acquisition channels, 2) 2 experiments per channel, 3) Key metrics to track, 4) Expected outcomes and risks. Keep the plan actionable and realistic for a small team.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-email-sequence-onboarding',
                'slug' => 'onboarding-email-sequence',
                'title' => 'Onboarding Email Sequence',
                'description' => 'Generate a multi-step onboarding email sequence for new users.',
                'image' => null,
                'meta_description' => 'Create onboarding email sequences using AI prompts. Welcome users, educate them, and drive activation.',
                'meta_keywords' => 'onboarding email prompts, email sequence ai, user activation emails, lifecycle marketing prompts',
                'prompt' => "Create a 5-email onboarding sequence for new users of: [PRODUCT OR SERVICE]. For each email, include: 1) Subject line, 2) Main message, 3) One clear CTA. Focus on activation, education, and early value realization.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-viral-campaign-ideas',
                'slug' => 'viral-campaign-ideas',
                'title' => 'Viral Campaign Ideas Generator',
                'description' => 'Generate creative viral marketing campaign ideas for brand awareness.',
                'image' => null,
                'meta_description' => 'Discover viral marketing campaign ideas using AI. Create shareable campaigns for brand growth.',
                'meta_keywords' => 'viral campaign ideas, marketing campaign prompts, growth marketing ai, viral marketing ideas',
                'prompt' => "Generate 10 creative viral campaign ideas for: [BRAND OR PRODUCT]. For each idea, include: 1) Core concept, 2) Hook, 3) Sharing mechanic, 4) Platform fit (TikTok, Instagram, X, YouTube). Optimize for shareability and low budget execution.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 4,
                'unique_id' => 'mkt-competitor-analysis',
                'slug' => 'competitor-analysis-generator',
                'title' => 'Competitor Analysis Generator',
                'description' => 'Generate a clear competitor analysis with positioning and gaps.',
                'image' => null,
                'meta_description' => 'Create competitor analysis using AI prompts. Identify strengths, weaknesses, and market gaps.',
                'meta_keywords' => 'competitor analysis ai, market research prompts, competitive analysis generator, marketing research ai',
                'prompt' => "Create a competitor analysis for: [YOUR PRODUCT] vs [COMPETITOR 1, COMPETITOR 2]. Include: 1) Positioning comparison, 2) Feature gaps, 3) Pricing differences, 4) Messaging strengths/weaknesses, 5) Opportunities to differentiate.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-startup-idea-validator',
                'slug' => 'startup-idea-validator',
                'title' => 'Startup Idea Validator',
                'description' => 'Validate a startup idea with problem, solution, market, and risks.',
                'image' => null,
                'meta_description' => 'Validate startup ideas using AI prompts. Analyze problem, solution, market demand, and risks.',
                'meta_keywords' => 'startup idea validation, business idea prompts, market validation ai, startup planning',
                'prompt' => "Validate the startup idea: [DESCRIBE IDEA]. Analyze: 1) Target problem and who has it, 2) Proposed solution and unique value, 3) Market demand and competitors, 4) Key risks and assumptions, 5) One quick validation experiment to run this week.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-mvp-feature-scope',
                'slug' => 'mvp-feature-scope',
                'title' => 'MVP Feature Scoping Assistant',
                'description' => 'Define the core features for an MVP without overbuilding.',
                'image' => null,
                'meta_description' => 'Scope MVP features using AI prompts. Identify core features, nice-to-haves, and risks.',
                'meta_keywords' => 'mvp scoping prompts, feature prioritization ai, mvp planning, product roadmap prompts',
                'prompt' => "Define the MVP scope for: [PRODUCT IDEA]. Provide: 1) Core must-have features (v1), 2) Nice-to-have features (later), 3) Features to avoid initially, 4) Key risks of overbuilding, 5) One metric to validate MVP success.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-lean-canvas-generator',
                'slug' => 'lean-canvas-generator',
                'title' => 'Lean Canvas Generator',
                'description' => 'Create a lean canvas to clarify business model and assumptions.',
                'image' => null,
                'meta_description' => 'Generate a lean canvas using AI prompts. Clarify problem, solution, and business model.',
                'meta_keywords' => 'lean canvas ai, business model canvas prompts, startup canvas generator, lean startup planning',
                'prompt' => "Create a Lean Canvas for: [STARTUP IDEA]. Fill out: Problem, Customer Segments, Unique Value Proposition, Solution, Channels, Revenue Streams, Cost Structure, Key Metrics, Unfair Advantage. Keep each section concise.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-pitch-deck-outline',
                'slug' => 'pitch-deck-outline',
                'title' => 'Pitch Deck Outline Generator',
                'description' => 'Generate a clear pitch deck outline for investors or partners.',
                'image' => null,
                'meta_description' => 'Create pitch deck outlines using AI prompts. Structure slides for problem, solution, traction, and vision.',
                'meta_keywords' => 'pitch deck ai, investor pitch prompts, startup pitch outline, pitch presentation generator',
                'prompt' => "Create a pitch deck outline for: [STARTUP IDEA]. Include slides for: Problem, Solution, Market Opportunity, Product Demo, Traction (or validation plan), Business Model, Go-to-Market, Competition, Roadmap, Ask. Add 1–2 bullet points per slide.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-gtm-strategy',
                'slug' => 'go-to-market-strategy',
                'title' => 'Go-To-Market Strategy Planner',
                'description' => 'Plan a realistic go-to-market strategy for launching a product.',
                'image' => null,
                'meta_description' => 'Generate go-to-market strategies using AI prompts. Plan channels, messaging, and launch steps.',
                'meta_keywords' => 'go to market strategy ai, product launch prompts, gtm plan generator, marketing launch ai',
                'prompt' => "Create a go-to-market strategy for launching: [PRODUCT]. Include: 1) Target customer profile, 2) Core message/value prop, 3) Primary launch channels, 4) 2–3 launch experiments, 5) Key metrics to track in the first 30 days.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 5,
                'unique_id' => 'biz-revenue-model-ideas',
                'slug' => 'revenue-model-ideas',
                'title' => 'Revenue Model Ideas Generator',
                'description' => 'Generate monetization ideas and pricing models for a product.',
                'image' => null,
                'meta_description' => 'Discover revenue model ideas using AI prompts. Explore pricing strategies and monetization options.',
                'meta_keywords' => 'revenue model ai, monetization prompts, pricing strategy ai, business model ideas',
                'prompt' => "Generate 5 monetization models for: [PRODUCT OR SERVICE]. For each model, include: 1) Pricing approach, 2) Target customer, 3) Pros/cons, 4) One experiment to validate willingness to pay.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-code-generator',
                'slug' => 'code-generator',
                'title' => 'Code Generator from Requirements',
                'description' => 'Generate clean, working code from a feature description.',
                'image' => null,
                'meta_description' => 'Generate code using AI prompts. Convert feature requirements into clean and structured code.',
                'meta_keywords' => 'code generator ai, ai coding prompts, generate code from description, programming assistant',
                'prompt' => "Generate production-ready code for the following feature: [DESCRIBE FEATURE]. Use [LANGUAGE/FRAMEWORK]. Include: 1) Clear file structure, 2) Core implementation, 3) Inline comments, 4) Example usage, 5) Basic error handling.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-code-reviewer',
                'slug' => 'code-reviewer',
                'title' => 'AI Code Reviewer',
                'description' => 'Review code for bugs, improvements, and best practices.',
                'image' => null,
                'meta_description' => 'Review code using AI prompts. Find bugs, security issues, and performance improvements.',
                'meta_keywords' => 'code review ai, ai code analysis, bug finding ai, refactor code prompts',
                'prompt' => "Review the following code: [PASTE CODE]. Analyze: 1) Bugs or logical issues, 2) Security risks, 3) Performance improvements, 4) Readability and structure, 5) Suggested refactored version.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-bug-finder',
                'slug' => 'bug-finder',
                'title' => 'Bug Finder & Fixer',
                'description' => 'Find and fix bugs in code with explanations.',
                'image' => null,
                'meta_description' => 'Find and fix bugs using AI prompts. Debug code with clear explanations and fixes.',
                'meta_keywords' => 'debug code ai, bug finder ai, fix code prompts, programming debugging assistant',
                'prompt' => "Debug the following code: [PASTE CODE]. 1) Identify the root cause of the bug, 2) Explain why it happens, 3) Provide the fixed code, 4) Suggest a test case to prevent this issue in the future.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-refactor-code',
                'slug' => 'refactor-code',
                'title' => 'Code Refactoring Assistant',
                'description' => 'Refactor messy or legacy code into clean and maintainable code.',
                'image' => null,
                'meta_description' => 'Refactor code using AI prompts. Improve readability, structure, and maintainability.',
                'meta_keywords' => 'refactor code ai, clean code prompts, improve code structure, legacy code refactor',
                'prompt' => "Refactor the following code: [PASTE CODE]. Improve: 1) Readability, 2) Maintainability, 3) Naming conventions, 4) Structure. Keep behavior the same and explain key changes briefly.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-system-design-helper',
                'slug' => 'system-design-helper',
                'title' => 'System Design Helper',
                'description' => 'Design scalable system architecture for apps and services.',
                'image' => null,
                'meta_description' => 'Design scalable systems using AI prompts. Plan architecture, components, and trade-offs.',
                'meta_keywords' => 'system design ai, software architecture prompts, scalable system design, backend architecture ai',
                'prompt' => "Design a scalable system for: [DESCRIBE APP]. Include: 1) High-level architecture, 2) Core components, 3) Database choice and schema outline, 4) API design, 5) Scalability and security considerations.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 6,
                'unique_id' => 'dev-api-docs-generator',
                'slug' => 'api-docs-generator',
                'title' => 'API Documentation Generator',
                'description' => 'Generate clean API documentation from endpoints.',
                'image' => null,
                'meta_description' => 'Generate API documentation using AI prompts. Create clear endpoint docs and examples.',
                'meta_keywords' => 'api documentation ai, generate api docs, swagger prompt ai, endpoint documentation generator',
                'prompt' => "Generate API documentation for the following endpoints: [PASTE ENDPOINTS OR CODE]. Include: 1) Endpoint purpose, 2) Request params, 3) Example requests, 4) Example responses, 5) Error cases.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-viral-post-generator',
                'slug' => 'viral-post-generator',
                'title' => 'Viral Social Media Post Generator',
                'description' => 'Generate high-engagement social media posts for any platform.',
                'image' => null,
                'meta_description' => 'Generate viral social media posts using AI prompts. Create engaging content for Twitter, LinkedIn, and Instagram.',
                'meta_keywords' => 'viral post ai, social media content generator, twitter prompts, instagram captions ai',
                'prompt' => "Create 5 viral post ideas for [PLATFORM] about [TOPIC]. Use: 1) Strong hooks, 2) Short and punchy copy, 3) Emojis where appropriate, 4) Clear call-to-action. Provide variations for different tones (educational, funny, controversial).",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-content-calendar',
                'slug' => 'content-calendar-generator',
                'title' => 'Content Calendar Generator',
                'description' => 'Plan a 30-day social media content calendar.',
                'image' => null,
                'meta_description' => 'Generate social media content calendars using AI prompts. Plan posts for 30 days with themes and formats.',
                'meta_keywords' => 'content calendar ai, social media planner prompts, 30 day content plan, content strategy ai',
                'prompt' => "Create a 30-day content calendar for [PLATFORM] in the niche: [NICHE]. For each day, include: 1) Post topic, 2) Content format (text, carousel, video), 3) Hook idea, 4) CTA. Keep it realistic for a solo creator.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-hashtag-generator',
                'slug' => 'hashtag-generator',
                'title' => 'Hashtag Generator',
                'description' => 'Generate optimized hashtags for social media posts.',
                'image' => null,
                'meta_description' => 'Generate optimized hashtags using AI prompts. Improve reach and discoverability on social platforms.',
                'meta_keywords' => 'hashtag generator ai, instagram hashtags ai, social media reach prompts, hashtag research ai',
                'prompt' => "Generate 20 optimized hashtags for [PLATFORM] about [TOPIC]. Include: 1) 5 high-volume hashtags, 2) 10 medium competition hashtags, 3) 5 niche-specific hashtags. Avoid banned or spammy tags.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-profile-optimizer',
                'slug' => 'profile-bio-optimizer',
                'title' => 'Profile Bio Optimizer',
                'description' => 'Optimize social media bios for clarity and conversions.',
                'image' => null,
                'meta_description' => 'Optimize social media bios using AI prompts. Improve profile clarity, positioning, and conversions.',
                'meta_keywords' => 'bio optimizer ai, profile bio prompts, twitter bio generator, instagram bio ai',
                'prompt' => "Rewrite this social media bio for [PLATFORM]: [PASTE CURRENT BIO]. Provide 3 optimized versions: 1) Professional, 2) Creator/Personal brand, 3) Fun & casual. Each version should include a clear value proposition and CTA.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-repurposing-content',
                'slug' => 'content-repurposer',
                'title' => 'Content Repurposing Assistant',
                'description' => 'Repurpose long-form content into social posts.',
                'image' => null,
                'meta_description' => 'Repurpose content using AI prompts. Turn blogs and videos into social media posts.',
                'meta_keywords' => 'content repurposing ai, turn blog into posts, content recycling prompts, social media repurpose ai',
                'prompt' => "Repurpose the following content into social media posts for [PLATFORM]: [PASTE CONTENT]. Create: 1) 3 short posts, 2) 1 carousel/thread outline, 3) 1 hook-only post. Keep it platform-native and engaging.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 7,
                'unique_id' => 'social-engagement-replies',
                'slug' => 'engagement-replies-generator',
                'title' => 'Engagement Reply Generator',
                'description' => 'Generate smart replies to comments and DMs.',
                'image' => null,
                'meta_description' => 'Generate replies to comments and DMs using AI prompts. Increase engagement and build community.',
                'meta_keywords' => 'comment reply ai, dm response generator, social media engagement prompts, community management ai',
                'prompt' => "Generate 5 reply options to this comment or DM: [PASTE MESSAGE]. Provide variations for: 1) Friendly, 2) Professional, 3) Short & punchy, 4) Value-adding, 5) CTA-driven. Avoid sounding robotic.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-daily-planner',
                'slug' => 'daily-planner',
                'title' => 'Daily Planner Generator',
                'description' => 'Create a realistic daily plan based on goals and energy levels.',
                'image' => null,
                'meta_description' => 'Generate daily plans using AI prompts. Plan tasks based on priorities and energy levels.',
                'meta_keywords' => 'daily planner ai, productivity prompts, task planning ai, time management prompts',
                'prompt' => "Create a realistic daily plan for me. Inputs: 1) Top 3 goals for today: [GOALS], 2) Available time: [HOURS], 3) Energy level (low/medium/high): [ENERGY]. Output a time-blocked plan with breaks and one high-impact task.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-weekly-review',
                'slug' => 'weekly-review',
                'title' => 'Weekly Review & Reset',
                'description' => 'Reflect on the week and plan improvements for the next one.',
                'image' => null,
                'meta_description' => 'Run weekly reviews using AI prompts. Reflect on wins, blockers, and plan improvements.',
                'meta_keywords' => 'weekly review ai, productivity reflection prompts, planning next week, weekly reset prompts',
                'prompt' => "Run a weekly review for me. Ask me 5 reflection questions about: wins, challenges, focus, habits, and lessons. Then help me create 3 priorities and 2 habit improvements for next week.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-goal-breakdown',
                'slug' => 'goal-breakdown',
                'title' => 'Big Goal Breakdown',
                'description' => 'Break a big goal into actionable steps and milestones.',
                'image' => null,
                'meta_description' => 'Break big goals into steps using AI prompts. Create milestones and action plans.',
                'meta_keywords' => 'goal breakdown ai, achieve goals prompts, milestone planning ai, productivity goal setting',
                'prompt' => "Break down this big goal: [GOAL]. Create: 1) 5–7 milestones, 2) Next 3 actionable steps, 3) Common obstacles, 4) A simple tracking method I can use weekly.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-focus-system',
                'slug' => 'focus-system-builder',
                'title' => 'Focus System Builder',
                'description' => 'Design a personal focus system to reduce distractions.',
                'image' => null,
                'meta_description' => 'Build focus systems using AI prompts. Reduce distractions and improve deep work.',
                'meta_keywords' => 'focus system ai, deep work prompts, distraction management, productivity focus',
                'prompt' => "Design a simple focus system for me. Inputs: 1) Main distractions: [DISTRACTIONS], 2) Work style: [DEEP WORK / SHORT BURSTS], 3) Typical day schedule: [SCHEDULE]. Output rules, tools, and a daily routine to stay focused.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-decision-helper',
                'slug' => 'decision-helper',
                'title' => 'Decision-Making Helper',
                'description' => 'Get clarity on tough personal or work decisions.',
                'image' => null,
                'meta_description' => 'Make better decisions using AI prompts. Analyze pros, cons, and trade-offs.',
                'meta_keywords' => 'decision making ai, clarity prompts, pros and cons ai, life decisions helper',
                'prompt' => "Help me decide between: [OPTION A] vs [OPTION B]. Analyze: 1) Pros & cons, 2) Short-term vs long-term impact, 3) Opportunity cost, 4) Which option aligns more with my goals: [GOALS]. End with a recommendation and why.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 8,
                'unique_id' => 'prod-habit-builder',
                'slug' => 'habit-builder',
                'title' => 'Habit Builder & Tracker',
                'description' => 'Build and track habits with a simple system.',
                'image' => null,
                'meta_description' => 'Build habits using AI prompts. Create simple systems for habit formation and tracking.',
                'meta_keywords' => 'habit building ai, habit tracker prompts, build habits with ai, personal development prompts',
                'prompt' => "Help me build the habit of: [HABIT]. Provide: 1) A tiny starting version of the habit, 2) A trigger to remind me, 3) A simple tracking method, 4) A reward system, 5) A plan for when I miss a day.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-product-description',
                'slug' => 'product-description-generator',
                'title' => 'Product Description Generator',
                'description' => 'Create high-converting product descriptions for online stores.',
                'image' => null,
                'meta_description' => 'Generate product descriptions using AI prompts. Write persuasive ecommerce copy that converts.',
                'meta_keywords' => 'product description ai, ecommerce copywriting prompts, product copy generator, shopify prompts',
                'prompt' => "Write a high-converting product description for: [PRODUCT NAME]. Include: 1) Benefit-driven headline, 2) 3–5 key benefits, 3) Feature-to-benefit mapping, 4) Objection handling, 5) Clear call-to-action. Target audience: [AUDIENCE].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-product-title-seo',
                'slug' => 'product-title-seo-optimizer',
                'title' => 'SEO Product Title Optimizer',
                'description' => 'Optimize product titles for SEO and marketplace ranking.',
                'image' => null,
                'meta_description' => 'Optimize ecommerce product titles using AI prompts. Improve SEO and marketplace visibility.',
                'meta_keywords' => 'seo product title ai, amazon product title prompts, ecommerce seo prompts, product listing ai',
                'prompt' => "Optimize the product title for SEO: [CURRENT TITLE]. Platform: [AMAZON / SHOPIFY / ETSY]. Include: 1) 5 optimized title variations, 2) Primary keyword, 3) Secondary keywords, 4) One recommended final version with reasoning.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-product-images-prompts',
                'slug' => 'product-image-prompts',
                'title' => 'Product Image Prompt Generator',
                'description' => 'Generate AI image prompts for ecommerce product photos.',
                'image' => null,
                'meta_description' => 'Generate AI image prompts for ecommerce product photography. Create studio and lifestyle shots.',
                'meta_keywords' => 'ai product images prompts, ecommerce image prompts, product photography ai prompts, midjourney ecommerce',
                'prompt' => "Create 5 AI image prompts for product photos of: [PRODUCT]. Include: 1) Clean studio shot, 2) Lifestyle usage scene, 3) Close-up detail shot, 4) Packaging shot, 5) Comparison or scale shot. Specify lighting, background, camera angle, and style.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-customer-support-replies',
                'slug' => 'customer-support-replies',
                'title' => 'Customer Support Reply Generator',
                'description' => 'Generate polite and helpful replies for customer inquiries.',
                'image' => null,
                'meta_description' => 'Generate customer support replies using AI prompts. Handle refunds, shipping, and FAQs.',
                'meta_keywords' => 'customer support ai, ecommerce support prompts, refund reply ai, customer service responses',
                'prompt' => "Generate 3 reply templates for this customer message: [PASTE MESSAGE]. Provide: 1) Friendly version, 2) Professional version, 3) Short & direct version. Ensure the tone is empathetic and solution-focused.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-upsell-cross-sell',
                'slug' => 'upsell-cross-sell-strategy',
                'title' => 'Upsell & Cross-Sell Strategy Generator',
                'description' => 'Create upsell and cross-sell strategies to increase AOV.',
                'image' => null,
                'meta_description' => 'Generate upsell and cross-sell strategies using AI prompts. Increase ecommerce average order value.',
                'meta_keywords' => 'upsell cross sell ai, ecommerce conversion prompts, increase aov ai, product bundling prompts',
                'prompt' => "Create an upsell and cross-sell strategy for: [PRODUCT]. Include: 1) 3 upsell ideas, 2) 3 cross-sell ideas, 3) Bundle suggestions, 4) Example copy for each, 5) One A/B test idea to validate impact.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 9,
                'unique_id' => 'ecom-email-campaigns',
                'slug' => 'ecommerce-email-campaigns',
                'title' => 'Ecommerce Email Campaign Generator',
                'description' => 'Generate email sequences for promotions and abandoned carts.',
                'image' => null,
                'meta_description' => 'Generate ecommerce email campaigns using AI prompts. Recover carts and run promotions.',
                'meta_keywords' => 'ecommerce email ai, abandoned cart email prompts, email marketing for ecommerce ai',
                'prompt' => "Create a 3-email sequence for: [CAMPAIGN TYPE – abandoned cart / product launch / discount]. Include subject lines, preview text, key message points, and CTA for each email. Keep tone aligned with brand voice: [BRAND VOICE].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-topic-explainer',
                'slug' => 'topic-explainer',
                'title' => 'Topic Explainer',
                'description' => 'Get a clear explanation of any topic at your level.',
                'image' => null,
                'meta_description' => 'Explain any topic using AI prompts. Learn complex topics in simple terms.',
                'meta_keywords' => 'topic explainer ai, explain like im five prompts, learn concepts ai, study helper ai',
                'prompt' => "Explain the topic: [TOPIC] at three levels: 1) Beginner, 2) Intermediate, 3) Advanced. Use simple examples and analogies. End with 3 key takeaways and 2 recommended next topics to learn.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-study-plan',
                'slug' => 'study-plan-generator',
                'title' => 'Personalized Study Plan Generator',
                'description' => 'Create a study plan based on goals and time availability.',
                'image' => null,
                'meta_description' => 'Generate personalized study plans using AI prompts. Plan learning schedules based on goals.',
                'meta_keywords' => 'study plan ai, learning schedule prompts, personalized learning plan ai, exam preparation prompts',
                'prompt' => "Create a personalized study plan for learning: [SUBJECT]. Inputs: 1) Current level: [LEVEL], 2) Goal: [GOAL], 3) Time available per week: [HOURS]. Output a weekly plan with milestones and resources to look for (no links needed).",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-summarizer',
                'slug' => 'content-summarizer',
                'title' => 'Content Summarizer',
                'description' => 'Summarize long articles, papers, or videos.',
                'image' => null,
                'meta_description' => 'Summarize content using AI prompts. Get key points from articles and videos.',
                'meta_keywords' => 'summarize ai, article summarizer prompts, research summary ai, notes generator ai',
                'prompt' => "Summarize the following content: [PASTE CONTENT]. Provide: 1) 5 bullet key points, 2) One-paragraph summary, 3) Actionable insights, 4) 3 follow-up questions for deeper understanding.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-notes-generator',
                'slug' => 'study-notes-generator',
                'title' => 'Study Notes Generator',
                'description' => 'Turn raw content into clean study notes.',
                'image' => null,
                'meta_description' => 'Generate study notes using AI prompts. Create structured notes for revision.',
                'meta_keywords' => 'study notes ai, note taking prompts, revision notes generator, learning notes ai',
                'prompt' => "Turn the following content into structured study notes: [PASTE CONTENT]. Use headings, bullet points, definitions, examples, and a short recap section at the end.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-research-questions',
                'slug' => 'research-questions-generator',
                'title' => 'Research Question Generator',
                'description' => 'Generate strong research questions for any topic.',
                'image' => null,
                'meta_description' => 'Generate research questions using AI prompts. Create focused and high-quality research questions.',
                'meta_keywords' => 'research questions ai, thesis topic prompts, research idea generator, academic prompts',
                'prompt' => "Generate 10 strong research questions about: [TOPIC]. Group them into: exploratory, comparative, and applied questions. Highlight 2 questions that are most promising and explain why.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 10,
                'unique_id' => 'learn-exam-prep',
                'slug' => 'exam-prep-helper',
                'title' => 'Exam Prep Helper',
                'description' => 'Prepare for exams with focused revision plans and questions.',
                'image' => null,
                'meta_description' => 'Prepare for exams using AI prompts. Create revision plans and practice questions.',
                'meta_keywords' => 'exam preparation ai, revision plan prompts, practice questions ai, study assistant prompts',
                'prompt' => "Help me prepare for an exam on: [SUBJECT]. Provide: 1) Key topics to focus on, 2) A 7-day revision plan, 3) 10 practice questions (mixed difficulty), 4) Common mistakes to avoid.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-workflow-designer',
                'slug' => 'workflow-designer',
                'title' => 'AI Workflow Designer',
                'description' => 'Design multi-step AI workflows for complex tasks.',
                'image' => null,
                'meta_description' => 'Design AI workflows using prompts. Build multi-step automation systems with AI agents.',
                'meta_keywords' => 'ai workflow design, automation prompts, ai agents workflow, multi step ai system',
                'prompt' => "Design a multi-step AI workflow for: [TASK]. Include: 1) Step-by-step process, 2) Inputs/outputs for each step, 3) Where to use AI vs manual steps, 4) Error handling and fallbacks, 5) How to evaluate output quality.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-agent-roles',
                'slug' => 'ai-agent-roles',
                'title' => 'AI Agent Roles Generator',
                'description' => 'Define roles and responsibilities for multiple AI agents.',
                'image' => null,
                'meta_description' => 'Define AI agent roles using prompts. Design multi-agent systems for workflows.',
                'meta_keywords' => 'ai agents roles, multi agent prompts, ai role definitions, agent workflow design',
                'prompt' => "Design a multi-agent setup for: [PROJECT]. Define: 1) Each agent’s role, 2) Responsibilities, 3) Input/output format, 4) How agents communicate, 5) Conflict resolution rules.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-task-breakdown',
                'slug' => 'task-breakdown-automation',
                'title' => 'Task Breakdown for Automation',
                'description' => 'Break complex tasks into automatable steps.',
                'image' => null,
                'meta_description' => 'Break tasks into automatable steps using AI prompts. Identify automation opportunities.',
                'meta_keywords' => 'task breakdown ai, automation planning prompts, workflow optimization ai, process automation prompts',
                'prompt' => "Break down the task: [TASK] into steps. Label each step as: automatable by AI, partially automatable, or manual. For automatable steps, suggest the type of AI prompt or tool needed.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-pipeline-optimizer',
                'slug' => 'pipeline-optimizer',
                'title' => 'Workflow Pipeline Optimizer',
                'description' => 'Optimize an existing AI workflow or process.',
                'image' => null,
                'meta_description' => 'Optimize AI workflows using prompts. Improve speed, cost, and reliability of pipelines.',
                'meta_keywords' => 'workflow optimization ai, pipeline optimization prompts, improve ai workflow, automation efficiency ai',
                'prompt' => "Review and optimize this workflow: [DESCRIBE CURRENT WORKFLOW]. Suggest improvements for: 1) Speed, 2) Cost efficiency, 3) Output quality, 4) Failure handling, 5) Scalability.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-no-code-workflows',
                'slug' => 'no-code-automation-ideas',
                'title' => 'No-Code AI Automation Ideas',
                'description' => 'Generate automation ideas using no-code tools and AI.',
                'image' => null,
                'meta_description' => 'Generate no-code AI automation ideas. Combine AI with no-code workflows.',
                'meta_keywords' => 'no code ai automation, workflow ideas ai, zapier ai prompts, automation ideas prompts',
                'prompt' => "Suggest 5 no-code AI automation ideas for: [USE CASE]. For each idea, include: 1) Trigger, 2) AI task, 3) Output action, 4) Value created, 5) One risk or limitation.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 11,
                'unique_id' => 'auto-evaluation-metrics',
                'slug' => 'ai-workflow-evaluation-metrics',
                'title' => 'AI Workflow Evaluation Metrics',
                'description' => 'Define metrics to measure AI workflow performance.',
                'image' => null,
                'meta_description' => 'Define evaluation metrics for AI workflows using prompts. Measure quality, speed, and reliability.',
                'meta_keywords' => 'ai workflow metrics, evaluate ai performance, automation metrics prompts, ai quality measurement',
                'prompt' => "Define evaluation metrics for this AI workflow: [WORKFLOW]. Include: 1) Quality metrics, 2) Speed/latency metrics, 3) Cost metrics, 4) Failure rate, 5) Human review checkpoints.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-system-prompt-builder',
                'slug' => 'system-prompt-builder',
                'title' => 'System Prompt Builder',
                'description' => 'Create powerful system prompts for consistent AI behavior.',
                'image' => null,
                'meta_description' => 'Build system prompts using AI. Control tone, rules, and output style for consistent results.',
                'meta_keywords' => 'system prompt ai, prompt engineering system messages, ai behavior control prompts',
                'prompt' => "Create a system prompt for an AI that will act as: [ROLE]. Define: 1) Tone and personality, 2) Rules and constraints, 3) Output format, 4) What the AI should refuse, 5) Examples of good vs bad responses.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-structured-output',
                'slug' => 'structured-output-prompts',
                'title' => 'Structured Output Prompt Generator',
                'description' => 'Force AI to respond in a strict, structured format.',
                'image' => null,
                'meta_description' => 'Generate structured output prompts for AI. Get JSON, tables, or bullet formats consistently.',
                'meta_keywords' => 'structured output ai, json output prompts, table output prompts, prompt formatting ai',
                'prompt' => "Rewrite this prompt to enforce structured output: [PASTE PROMPT]. The output must be valid JSON with fields: [FIELD1, FIELD2, FIELD3]. Add constraints to avoid extra text.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-few-shot-examples',
                'slug' => 'few-shot-examples-builder',
                'title' => 'Few-Shot Example Builder',
                'description' => 'Improve results by adding few-shot examples to prompts.',
                'image' => null,
                'meta_description' => 'Build few-shot examples using AI prompts. Improve accuracy with examples.',
                'meta_keywords' => 'few shot prompting, example based prompts, prompt engineering examples, ai few shot prompts',
                'prompt' => "Convert this task into a few-shot prompt: [TASK]. Provide 2–3 high-quality input/output examples that demonstrate the desired behavior and edge cases.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-prompt-debugger',
                'slug' => 'prompt-debugger',
                'title' => 'Prompt Debugger',
                'description' => 'Fix prompts that produce poor or inconsistent results.',
                'image' => null,
                'meta_description' => 'Debug prompts using AI. Improve clarity, constraints, and reliability.',
                'meta_keywords' => 'prompt debugging ai, fix prompts, improve ai prompt quality, prompt optimization',
                'prompt' => "Analyze this prompt that gives bad results: [PASTE PROMPT]. Identify why it fails, then rewrite it with clearer instructions, constraints, and an example. Explain the changes briefly.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-chain-of-thought-lite',
                'slug' => 'step-by-step-reasoning-prompt',
                'title' => 'Step-by-Step Reasoning Prompt',
                'description' => 'Encourage better reasoning without leaking chain-of-thought.',
                'image' => null,
                'meta_description' => 'Design prompts that encourage step-by-step reasoning while keeping concise outputs.',
                'meta_keywords' => 'step by step reasoning prompts, reasoning ai prompts, chain of thought prompts, ai reasoning control',
                'prompt' => "Rewrite this prompt to encourage careful reasoning without revealing chain-of-thought. The AI should: 1) Think internally step-by-step, 2) Output only the final concise answer with a short justification. Prompt: [PASTE PROMPT].",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 12,
                'unique_id' => 'pe-evaluation-harness',
                'slug' => 'prompt-evaluation-harness',
                'title' => 'Prompt Evaluation Harness',
                'description' => 'Create test cases to evaluate prompt quality and consistency.',
                'image' => null,
                'meta_description' => 'Evaluate prompt quality using AI. Build test cases to measure reliability and edge cases.',
                'meta_keywords' => 'prompt evaluation ai, test prompts, prompt quality metrics, ai prompt testing',
                'prompt' => "Create a prompt evaluation harness for: [PROMPT]. Generate: 1) 5 normal test cases, 2) 3 edge cases, 3) 2 adversarial inputs, 4) A simple scoring rubric to judge output quality.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-story-generator',
                'slug' => 'short-story-generator',
                'title' => 'Short Story Generator',
                'description' => 'Create a short, creative story in any genre.',
                'image' => null,
                'meta_description' => 'Generate short stories using AI prompts. Create creative fiction in any genre.',
                'meta_keywords' => 'short story ai, creative writing prompts, fiction generator ai, storytelling prompts',
                'prompt' => "Write a short story in the genre: [GENRE]. Include: 1) A unique main character, 2) A surprising twist, 3) A vivid setting, 4) A meaningful ending. Tone: [TONE]. Length: 300–500 words.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-roleplay-character',
                'slug' => 'roleplay-character-creator',
                'title' => 'Roleplay Character Creator',
                'description' => 'Create a detailed character for roleplay or stories.',
                'image' => null,
                'meta_description' => 'Create roleplay characters using AI prompts. Generate detailed backstories and personalities.',
                'meta_keywords' => 'roleplay character ai, character generator prompts, dnd character ai, story character creator',
                'prompt' => "Create a detailed roleplay character for: [SETTING]. Include: 1) Name, 2) Backstory, 3) Personality traits, 4) Strengths and flaws, 5) A secret or twist. Provide 2 hooks for story or gameplay.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-game-ideas',
                'slug' => 'mini-game-ideas',
                'title' => 'Mini Game Ideas Generator',
                'description' => 'Generate fun mini-game ideas for apps or parties.',
                'image' => null,
                'meta_description' => 'Generate mini-game ideas using AI prompts. Create fun games for apps, events, or parties.',
                'meta_keywords' => 'game ideas ai, mini game prompts, party game ideas, fun app ideas ai',
                'prompt' => "Generate 5 fun mini-game ideas for: [CONTEXT – app / party / classroom]. For each idea, include: 1) Objective, 2) Rules, 3) Win condition, 4) Why it’s fun, 5) One twist to make it more addictive.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-lyrics-writer',
                'slug' => 'song-lyrics-writer',
                'title' => 'Song Lyrics Generator',
                'description' => 'Write original song lyrics in any style or mood.',
                'image' => null,
                'meta_description' => 'Generate song lyrics using AI prompts. Write creative lyrics in any style.',
                'meta_keywords' => 'song lyrics ai, lyric generator prompts, creative music writing ai, songwriting prompts',
                'prompt' => "Write original song lyrics in the style of: [STYLE or GENRE] (do not copy any existing lyrics). Theme: [THEME]. Mood: [MOOD]. Structure: verse–chorus–verse–bridge–chorus.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-creative-challenges',
                'slug' => 'creative-challenges',
                'title' => 'Creative Challenge Generator',
                'description' => 'Get daily or weekly creative challenges to spark ideas.',
                'image' => null,
                'meta_description' => 'Generate creative challenges using AI prompts. Spark creativity with daily prompts.',
                'meta_keywords' => 'creative challenges ai, daily creativity prompts, art challenges ai, writing challenges prompts',
                'prompt' => "Create 7 creative challenges (one per day) for: [CREATIVE AREA – writing / art / video]. Each challenge should be simple, fun, and doable in under 30 minutes. Add one optional stretch goal per challenge.",
                'prompt_version' => '1.0',
            ],
            [
                'ai_prompt_category_id' => 13,
                'unique_id' => 'fun-roast-me',
                'slug' => 'playful-roast',
                'title' => 'Playful Roast Generator',
                'description' => 'Get a lighthearted, non-offensive roast for fun.',
                'image' => null,
                'meta_description' => 'Generate playful, non-offensive roasts using AI prompts. Keep it fun and friendly.',
                'meta_keywords' => 'funny roast ai, playful insults ai, harmless roast prompts, humor ai prompts',
                'prompt' => "Give me a playful, non-offensive roast about: [TRAIT or HABIT]. Keep it lighthearted, funny, and supportive at the end. Avoid insults about appearance, identity, or sensitive topics.",
                'prompt_version' => '1.0',
            ]
        ];

        foreach ($prompts as $p) {
            AiPrompt::updateOrCreate(
                ['unique_id' => $p['unique_id']],
                array_merge($p, ['copy_count' => 0, 'is_active' => true])
            );
        }
    }
}
