<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PlaceCategory;

class PlaceCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            ['id' => '1', 'name' => 'accounting', 'is_active' => '0'],
            ['id' => '2', 'name' => 'airport', 'is_active' => '0'],
            ['id' => '3', 'name' => 'amusement_park', 'is_active' => '0'],
            ['id' => '4', 'name' => 'aquarium', 'is_active' => '0'],
            ['id' => '5', 'name' => 'art_gallery', 'is_active' => '0'],
            ['id' => '6', 'name' => 'atm', 'is_active' => '0'],
            ['id' => '7', 'name' => 'bakery', 'is_active' => '1'],
            ['id' => '8', 'name' => 'bank', 'is_active' => '0'],
            ['id' => '9', 'name' => 'bar', 'is_active' => '0'],
            ['id' => '10', 'name' => 'beauty_salon', 'is_active' => '1'],
            ['id' => '11', 'name' => 'bicycle_store', 'is_active' => '0'],
            ['id' => '12', 'name' => 'book_store', 'is_active' => '0'],
            ['id' => '13', 'name' => 'bowling_alley', 'is_active' => '0'],
            ['id' => '14', 'name' => 'bus_station', 'is_active' => '0'],
            ['id' => '15', 'name' => 'cafe', 'is_active' => '1'],
            ['id' => '16', 'name' => 'campground', 'is_active' => '0'],
            ['id' => '17', 'name' => 'car_dealer', 'is_active' => '1'],
            ['id' => '18', 'name' => 'car_rental', 'is_active' => '0'],
            ['id' => '19', 'name' => 'car_repair', 'is_active' => '0'],
            ['id' => '20', 'name' => 'car_wash', 'is_active' => '0'],
            ['id' => '21', 'name' => 'casino', 'is_active' => '0'],
            ['id' => '22', 'name' => 'cemetery', 'is_active' => '0'],
            ['id' => '23', 'name' => 'church', 'is_active' => '0'],
            ['id' => '24', 'name' => 'city_hall', 'is_active' => '0'],
            ['id' => '25', 'name' => 'clothing_store', 'is_active' => '1'],
            ['id' => '26', 'name' => 'convenience_store', 'is_active' => '0'],
            ['id' => '27', 'name' => 'courthouse', 'is_active' => '0'],
            ['id' => '28', 'name' => 'dentist', 'is_active' => '0'],
            ['id' => '29', 'name' => 'department_store', 'is_active' => '0'],
            ['id' => '30', 'name' => 'doctor', 'is_active' => '1'],
            ['id' => '31', 'name' => 'drugstore', 'is_active' => '1'],
            ['id' => '32', 'name' => 'electrician', 'is_active' => '0'],
            ['id' => '33', 'name' => 'electronics_store', 'is_active' => '1'],
            ['id' => '34', 'name' => 'embassy', 'is_active' => '0'],
            ['id' => '35', 'name' => 'fire_station', 'is_active' => '0'],
            ['id' => '36', 'name' => 'florist', 'is_active' => '0'],
            ['id' => '37', 'name' => 'funeral_home', 'is_active' => '0'],
            ['id' => '38', 'name' => 'furniture_store', 'is_active' => '1'],
            ['id' => '39', 'name' => 'gas_station', 'is_active' => '0'],
            ['id' => '40', 'name' => 'gym', 'is_active' => '1'],
            ['id' => '41', 'name' => 'hair_care', 'is_active' => '1'],
            ['id' => '42', 'name' => 'hardware_store', 'is_active' => '0'],
            ['id' => '43', 'name' => 'hindu_temple', 'is_active' => '0'],
            ['id' => '44', 'name' => 'home_goods_store', 'is_active' => '1'],
            ['id' => '45', 'name' => 'hospital', 'is_active' => '0'],
            ['id' => '46', 'name' => 'insurance_agency', 'is_active' => '1'],
            ['id' => '47', 'name' => 'jewelry_store', 'is_active' => '1'],
            ['id' => '48', 'name' => 'laundry', 'is_active' => '1'],
            ['id' => '49', 'name' => 'lawyer', 'is_active' => '1'],
            ['id' => '50', 'name' => 'library', 'is_active' => '0'],
            ['id' => '51', 'name' => 'light_rail_station', 'is_active' => '0'],
            ['id' => '52', 'name' => 'liquor_store', 'is_active' => '0'],
            ['id' => '53', 'name' => 'local_government_office', 'is_active' => '0'],
            ['id' => '54', 'name' => 'locksmith', 'is_active' => '0'],
            ['id' => '55', 'name' => 'lodging', 'is_active' => '0'],
            ['id' => '56', 'name' => 'meal_delivery', 'is_active' => '0'],
            ['id' => '57', 'name' => 'meal_takeaway', 'is_active' => '0'],
            ['id' => '58', 'name' => 'mosque', 'is_active' => '0'],
            ['id' => '59', 'name' => 'movie_rental', 'is_active' => '0'],
            ['id' => '60', 'name' => 'movie_theater', 'is_active' => '1'],
            ['id' => '61', 'name' => 'moving_company', 'is_active' => '0'],
            ['id' => '62', 'name' => 'museum', 'is_active' => '0'],
            ['id' => '63', 'name' => 'night_club', 'is_active' => '0'],
            ['id' => '64', 'name' => 'painter', 'is_active' => '1'],
            ['id' => '65', 'name' => 'park', 'is_active' => '0'],
            ['id' => '66', 'name' => 'parking', 'is_active' => '0'],
            ['id' => '67', 'name' => 'pet_store', 'is_active' => '0'],
            ['id' => '68', 'name' => 'pharmacy', 'is_active' => '1'],
            ['id' => '69', 'name' => 'physiotherapist', 'is_active' => '0'],
            ['id' => '70', 'name' => 'plumber', 'is_active' => '1'],
            ['id' => '71', 'name' => 'police', 'is_active' => '0'],
            ['id' => '72', 'name' => 'post_office', 'is_active' => '0'],
            ['id' => '73', 'name' => 'primary_school', 'is_active' => '0'],
            ['id' => '74', 'name' => 'real_estate_agency', 'is_active' => '1'],
            ['id' => '75', 'name' => 'restaurant', 'is_active' => '1'],
            ['id' => '76', 'name' => 'roofing_contractor', 'is_active' => '0'],
            ['id' => '77', 'name' => 'rv_park', 'is_active' => '0'],
            ['id' => '78', 'name' => 'school', 'is_active' => '1'],
            ['id' => '79', 'name' => 'secondary_school', 'is_active' => '0'],
            ['id' => '80', 'name' => 'shoe_store', 'is_active' => '1'],
            ['id' => '81', 'name' => 'shopping_mall', 'is_active' => '0'],
            ['id' => '82', 'name' => 'spa', 'is_active' => '1'],
            ['id' => '83', 'name' => 'stadium', 'is_active' => '0'],
            ['id' => '84', 'name' => 'storage', 'is_active' => '0'],
            ['id' => '85', 'name' => 'store', 'is_active' => '0'],
            ['id' => '86', 'name' => 'subway_station', 'is_active' => '0'],
            ['id' => '87', 'name' => 'supermarket', 'is_active' => '0'],
            ['id' => '88', 'name' => 'synagogue', 'is_active' => '0'],
            ['id' => '89', 'name' => 'taxi_stand', 'is_active' => '0'],
            ['id' => '90', 'name' => 'tourist_attraction', 'is_active' => '0'],
            ['id' => '91', 'name' => 'train_station', 'is_active' => '0'],
            ['id' => '92', 'name' => 'transit_station', 'is_active' => '0'],
            ['id' => '93', 'name' => 'travel_agency', 'is_active' => '0'],
            ['id' => '94', 'name' => 'university', 'is_active' => '1'],
            ['id' => '95', 'name' => 'veterinary_care', 'is_active' => '0'],
            ['id' => '96', 'name' => 'zoo', 'is_active' => '0'],
            ['id' => '97', 'name' => 'computer_training_institutes', 'is_active' => '0'],
            ['id' => '98', 'name' => 'courier_services', 'is_active' => '0'],
            ['id' => '99', 'name' => 'interior_designers', 'is_active' => '0'],
            ['id' => '100', 'name' => 'driving_schools', 'is_active' => '0'],
            ['id' => '101', 'name' => 'printing_services', 'is_active' => '0'],
            ['id' => '102', 'name' => 'investment_agencies', 'is_active' => '1'],
            ['id' => '103', 'name' => 'mutual_fund_consultants', 'is_active' => '0'],
            ['id' => '104', 'name' => 'loan_consultants', 'is_active' => '1'],
            ['id' => '105', 'name' => 'financial_planners', 'is_active' => '1'],
            ['id' => '106', 'name' => 'tax_consultants', 'is_active' => '1'],
            ['id' => '107', 'name' => 'chartered_accountants', 'is_active' => '0'],
            ['id' => '108', 'name' => 'law_firms', 'is_active' => '0'],
            ['id' => '109', 'name' => 'software_companies', 'is_active' => '1'],
            ['id' => '110', 'name' => 'web_development_agencies', 'is_active' => '1'],
            ['id' => '111', 'name' => 'digital_marketing_agencies', 'is_active' => '1'],
            ['id' => '112', 'name' => 'advertising_agencies', 'is_active' => '1'],
            ['id' => '113', 'name' => 'placement_consultants', 'is_active' => '0'],
            ['id' => '114', 'name' => 'pools_and_water_parks', 'is_active' => '0'],
            ['id' => '115', 'name' => 'fitness_equipment_stores', 'is_active' => '0'],
            ['id' => '116', 'name' => 'packers_and_movers', 'is_active' => '0'],
            ['id' => '117', 'name' => 'kids_play_areas', 'is_active' => '0'],
        ];

        foreach ($types as $type) {

            $type['label'] = ucwords(str_replace('_', ' ', $type['name']));

            PlaceCategory::updateOrCreate(
                ['id' => $type['id']],
                $type
            );
        }
    }
}
